### ISSUE TITLE
Test wrapper breaks abstract transpiler tests

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/benchpress#21]
Currently the abstract transpiler tests are failing using the wrapper pytest-benchmark branch.  Moving to the standard `pytest-benchmark` package fixes this.  The device transpile routines are fine, so I am not sure where the issue is coming from.

**Comment by nonhermitian** [comment]
This looks to be resolved, at least on Linux, as verified by explicitly making new envs for each SDK

**Comment by 1ucian0** [comment]
Different branches for different approaches (see https://pypi.org/project/wrapt-timeout-decorator/#set-subprocess-starting-method)
 * [`timeout-skiplist/auto/decorator`](https://github.com/1ucian0/pytest-benchmark/tree/timeout-skiplist/auto/decorator): Uses `timeout` decorator internally, without setting method with `set_subprocess_starting_method`
 * [`timeout-skiplist/fork/decorator`](https://github.com/1ucian0/pytest-benchmark/tree/timeout-skiplist/fork/decorator): Uses `timeout` decorator internally and `fork` method
 * [`timeout-skiplist/forkserver/decorator`](https://github.com/1ucian0/pytest-benchmark/tree/timeout-skiplist/forkserver/decorator): Uses `timeout` decorator internally and `forkserver` method
  * [`timeout-skiplist/spawn/decorator`](https://github.com/1ucian0/pytest-benchmark/tree/timeout-skiplist/spawn/decorator): Uses `timeout` decorator internally and `spawn` method
