### ISSUE TITLE
Add Amazon Braket and cirq requirements files

### ISSUE THREAD

**Issue by jordandsullivan** [Qiskit/benchpress#3]
Currently the directions to test out Benchpress are as follows: `python -m pytest --benchmark-min-rounds=1 benchpress/*_gym` which includes the [Amazon Braket gym](https://github.com/Qiskit/benchpress/tree/main/benchpress/braket_gym) and [Cirq gym](https://github.com/Qiskit/benchpress/tree/main/benchpress/cirq_gym); however, these two are not included in any of the requirements files.

**Comment by nonhermitian** [comment]
Yes, we have not kept up to date with those sdks as of late since they have a larger disparity with Qiskit.  It is on the list of things to do though.
